name: WebHostMost Login  

on:
  schedule:
    # 每月20号的 UTC 时间 00:00 运行
    - cron: '0 0 20 * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install puppeteer@latest

      - name: Run login script
        env:
          USERNAME_AND_PASSWORD: ${{ secrets.USERNAME_AND_PASSWORD }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: node scripts/login.js
